// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "InputCodes.generated.h"



UENUM(BlueprintType)
enum class InputCodeBT : uint8
{
	None  UMETA(DisplayName = "None"),
	BackSpace  UMETA(DisplayName = "BackSpace"),
	Tab		UMETA(DisplayName = "Tab"),
	Enter		UMETA(DisplayName = "Enter"),
	Pause		UMETA(DisplayName = "Pause"),

	CapsLock  UMETA(DisplayName = "CapsLock"),
	Escape  UMETA(DisplayName = "Escape"),
	SpaceBar  UMETA(DisplayName = "SpaceBar"),
	PageUp  UMETA(DisplayName = "PageUp"),
	PageDown  UMETA(DisplayName = "PageDown"),
	End  UMETA(DisplayName = "End"),
	Home  UMETA(DisplayName = "Home"),

	Up  UMETA(DisplayName = "Up"),
	Down  UMETA(DisplayName = "Down"),
	Left  UMETA(DisplayName = "Left"),
	Right  UMETA(DisplayName = "Right"),

	Insert  UMETA(DisplayName = "Insert"),
	Delete  UMETA(DisplayName = "Delete"),

	Zero  UMETA(DisplayName = "Zero"),
	One  UMETA(DisplayName = "One"),
	Two  UMETA(DisplayName = "Two"),
	Three  UMETA(DisplayName = "Three"),
	Four  UMETA(DisplayName = "Four"),
	Five  UMETA(DisplayName = "Five"),
	Six  UMETA(DisplayName = "Six"),
	Seven  UMETA(DisplayName = "Seven"),
	Eight  UMETA(DisplayName = "Eight"),
	Nine  UMETA(DisplayName = "Nine"),

	A  UMETA(DisplayName = "A"),
	B  UMETA(DisplayName = "B"),
	C  UMETA(DisplayName = "C"),
	D  UMETA(DisplayName = "D"),
	E  UMETA(DisplayName = "E"),
	F  UMETA(DisplayName = "F"),
	G  UMETA(DisplayName = "G"),
	H  UMETA(DisplayName = "H"),
	I  UMETA(DisplayName = "I"),
	J  UMETA(DisplayName = "J"),
	K  UMETA(DisplayName = "K"),
	L  UMETA(DisplayName = "L"),
	M  UMETA(DisplayName = "M"),
	N  UMETA(DisplayName = "N"),
	O  UMETA(DisplayName = "O"),
	P  UMETA(DisplayName = "P"),
	Q  UMETA(DisplayName = "Q"),
	R	UMETA(DisplayName = "R"),
	S  UMETA(DisplayName = "S"),
	T  UMETA(DisplayName = "T"),
	U	UMETA(DisplayName = "U"),
	V  UMETA(DisplayName = "V"),
	W  UMETA(DisplayName = "W"),
	X  UMETA(DisplayName = "X"),
	Y  UMETA(DisplayName = "Y"),
	Z  UMETA(DisplayName = "Z"),

	NumPadZero  UMETA(DisplayName = "NumPadZero"),
	NumPadOne  UMETA(DisplayName = "NumPadOne"),
	NumPadTwo  UMETA(DisplayName = "NumPadTwo"),
	NumPadThree  UMETA(DisplayName = "NumPadThree"),
	NumPadFour  UMETA(DisplayName = "NumPadFour"),
	NumPadFive  UMETA(DisplayName = "NumPadFive"),
	NumPadSix  UMETA(DisplayName = "NumPadSix"),
	NumPadSeven  UMETA(DisplayName = "NumPadSeven"),
	NumPadEight  UMETA(DisplayName = "NumPadEight"),
	NumPadNine  UMETA(DisplayName = "NumPadNine"),

	Multiply  UMETA(DisplayName = "Multiply"),
	Add  UMETA(DisplayName = "Add"),
	Subtract  UMETA(DisplayName = "Subtract"),
	Decimal  UMETA(DisplayName = "Decimal"),
	Divide  UMETA(DisplayName = "Divide"),

	F1  UMETA(DisplayName = "F1"),
	F2  UMETA(DisplayName = "F2"),
	F3  UMETA(DisplayName = "F3"),
	F4  UMETA(DisplayName = "F4"),
	F5  UMETA(DisplayName = "F5"),
	F6  UMETA(DisplayName = "F6"),
	F7  UMETA(DisplayName = "F7"),
	F8  UMETA(DisplayName = "F8"),
	F9  UMETA(DisplayName = "F9"),
	F10  UMETA(DisplayName = "F10"),
	F11  UMETA(DisplayName = "F11"),
	F12  UMETA(DisplayName = "F12"),

	NumLock  UMETA(DisplayName = "NumLock"),

	ScrollLock  UMETA(DisplayName = "ScrollLock"),

	LeftShift  UMETA(DisplayName = "LeftShift"),
	RightShift  UMETA(DisplayName = "RightShift"),
	LeftControl  UMETA(DisplayName = "LeftControl"),
	RightControl  UMETA(DisplayName = "RightControl"),
	LeftAlt  UMETA(DisplayName = "LeftAlt"),
	RightAlt  UMETA(DisplayName = "RightAlt"),
	LeftCommand  UMETA(DisplayName = "LeftCommand"),
	RightCommand  UMETA(DisplayName = "RightCommand"),

	Semicolon  UMETA(DisplayName = "Semicolon"),
	Equals  UMETA(DisplayName = "Equals"),
	Comma  UMETA(DisplayName = "Comma"),
	Underscore  UMETA(DisplayName = "Underscore"),
	Hyphen  UMETA(DisplayName = "Hyphen"),
	Period  UMETA(DisplayName = "Period"),
	Slash  UMETA(DisplayName = "Slash"),
	Tilde  UMETA(DisplayName = "Tilde"),
	LeftBracket  UMETA(DisplayName = "LeftBracket"),
	Backslash  UMETA(DisplayName = "Backslash"),
	RightBracket  UMETA(DisplayName = "RightBracket"),
	Apostrophe  UMETA(DisplayName = "Apostrophe"),

	LeftMouseButton  UMETA(DisplayName = "LeftMouseButton"),
	RightMouseButton  UMETA(DisplayName = "RightMouseButton"),
	MiddleMouseButton  UMETA(DisplayName = "MiddleMouseButton"),
	ThumbMouseButton  UMETA(DisplayName = "ThumbMouseButton"),
	ThumbMouseButton2  UMETA(DisplayName = "ThumbMouseButton2"),

	Gamepad_FaceButton_Bottom  UMETA(DisplayName = "Gamepad_FaceButton_Bottom"),
	Gamepad_FaceButton_Right  UMETA(DisplayName = "Gamepad_FaceButton_Right"),
	Gamepad_FaceButton_Left  UMETA(DisplayName = "Gamepad_FaceButton_Left"),
	Gamepad_FaceButton_Top  UMETA(DisplayName = "Gamepad_FaceButton_Top"),
	Gamepad_Special_Left UMETA(DisplayName = "Gamepad_Special_Left"),
	Gamepad_Special_Right UMETA(DisplayName = "Gamepad_Special_Right"),

	Gamepad_LeftShoulder UMETA(DisplayName = "Gamepad_LeftShoulder"),
	Gamepad_RightShoulder UMETA(DisplayName = "Gamepad_RightShoulder"),
	Gamepad_LeftTrigger UMETA(DisplayName = "Gamepad_LeftTrigger"),
	Gamepad_RightTrigger UMETA(DisplayName = "Gamepad_RightTrigger"),
	Gamepad_LeftThumbstick UMETA(DisplayName = "Gamepad_LeftThumbstick"),
	Gamepad_RightThumbstick UMETA(DisplayName = "Gamepad_RightThumbstick"),
	Gamepad_DPad_Up UMETA(DisplayName = "Gamepad_DPad_Up"),
	Gamepad_DPad_Down UMETA(DisplayName = "Gamepad_DPad_Down"),
	Gamepad_DPad_Left UMETA(DisplayName = "Gamepad_DPad_Left"),
	Gamepad_DPad_Right UMETA(DisplayName = "Gamepad_DPad_Right"),
	Gamepad_LeftStick_Up UMETA(DisplayName = "Gamepad_LeftStick_Up"),
	Gamepad_LeftStick_Down UMETA(DisplayName = "Gamepad_LeftStick_Down"),
	Gamepad_LeftStick_Left UMETA(DisplayName = "Gamepad_LeftStick_Left"),
	Gamepad_LeftStick_Right UMETA(DisplayName = "Gamepad_LeftStick_Right"),
	Gamepad_RightStick_Up UMETA(DisplayName = "Gamepad_RightStick_Up"),
	Gamepad_RightStick_Down UMETA(DisplayName = "Gamepad_RightStick_Down"),
	Gamepad_RightStick_Left UMETA(DisplayName = "Gamepad_RightStick_Left"),
	Gamepad_RightStick_Right UMETA(DisplayName = "Gamepad_RightStick_Right"),
	MAX UMETA(DisplayName = "MAX"),
};

UENUM(BlueprintType)
enum class InputCodeAX : uint8
{
	None  UMETA(DisplayName = "None"),
	MouseX  UMETA(DisplayName = "MouseX"),
	MouseY  UMETA(DisplayName = "MouseY"),
	Gamepad_LeftX  UMETA(DisplayName = "GamepadLeftX"),
	Gamepad_LeftY  UMETA(DisplayName = "GamepadLeftY"),
	Gamepad_RightX  UMETA(DisplayName = "GamepadRightX"),
	Gamepad_RightY  UMETA(DisplayName = "GamepadRightY"),
	MAX UMETA(DisplayName = "MAX"),
};