// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "EInputBT.generated.h"


UENUM(BlueprintType)
enum EInputBT
{
	EInputBT_BackSpace  UMETA(DisplayName = "BackSpace"),
	EInputBT_Tab		UMETA(DisplayName = "Tab"),
	EInputBT_Enter		UMETA(DisplayName = "Enter"),
	EInputBT_Pause		UMETA(DisplayName = "Pause"),

	EInputBT_CapsLock  UMETA(DisplayName = "CapsLock"),
	EInputBT_Escape  UMETA(DisplayName = "Escape"),
	EInputBT_SpaceBar  UMETA(DisplayName = "SpaceBar"),
	EInputBT_PageUp  UMETA(DisplayName = "PageUp"),
	EInputBT_PageDown  UMETA(DisplayName = "PageDown"),
	EInputBT_End  UMETA(DisplayName = "End"),
	EInputBT_Home  UMETA(DisplayName = "Home"),

	EInputBT_Up  UMETA(DisplayName = "Up"),
	EInputBT_Down  UMETA(DisplayName = "Down"),
	EInputBT_Left  UMETA(DisplayName = "Left"),
	EInputBT_Right  UMETA(DisplayName = "Right"),

	EInputBT_Insert  UMETA(DisplayName = "Insert"),
	EInputBT_Delete  UMETA(DisplayName = "Delete"),

	EInputBT_Zero  UMETA(DisplayName = "Zero"),
	EInputBT_One  UMETA(DisplayName = "One"),
	EInputBT_Two  UMETA(DisplayName = "Two"),
	EInputBT_Three  UMETA(DisplayName = "Three"),
	EInputBT_Four  UMETA(DisplayName = "Four"),
	EInputBT_Five  UMETA(DisplayName = "Five"),
	EInputBT_Six  UMETA(DisplayName = "Six"),
	EInputBT_Seven  UMETA(DisplayName = "Seven"),
	EInputBT_Eight  UMETA(DisplayName = "Eight"),
	EInputBT_Nine  UMETA(DisplayName = "Nine"),

	EInputBT_A  UMETA(DisplayName = "A"),
	EInputBT_B  UMETA(DisplayName = "B"),
	EInputBT_C  UMETA(DisplayName = "C"),
	EInputBT_D  UMETA(DisplayName = "D"),
	EInputBT_E  UMETA(DisplayName = "E"),
	EInputBT_F  UMETA(DisplayName = "F"),
	EInputBT_G  UMETA(DisplayName = "G"),
	EInputBT_H  UMETA(DisplayName = "H"),
	EInputBT_I  UMETA(DisplayName = "I"),
	EInputBT_J  UMETA(DisplayName = "J"),
	EInputBT_K  UMETA(DisplayName = "K"),
	EInputBT_L  UMETA(DisplayName = "L"),
	EInputBT_M  UMETA(DisplayName = "M"),
	EInputBT_N  UMETA(DisplayName = "N"),
	EInputBT_O  UMETA(DisplayName = "O"),
	EInputBT_P  UMETA(DisplayName = "P"),
	EInputBT_Q  UMETA(DisplayName = "Q"),
	EInputBT_R	UMETA(DisplayName = "R"),
	EInputBT_S  UMETA(DisplayName = "S"),
	EInputBT_T  UMETA(DisplayName = "T"),
	EInputBT_U	UMETA(DisplayName = "U"),
	EInputBT_V  UMETA(DisplayName = "V"),
	EInputBT_W  UMETA(DisplayName = "W"),
	EInputBT_X  UMETA(DisplayName = "X"),
	EInputBT_Y  UMETA(DisplayName = "Y"),
	EInputBT_Z  UMETA(DisplayName = "Z"),

	EInputBT_NumPadZero  UMETA(DisplayName = "NumPadZero"),
	EInputBT_NumPadOne  UMETA(DisplayName = "NumPadOne"),
	EInputBT_NumPadTwo  UMETA(DisplayName = "NumPadTwo"),
	EInputBT_NumPadThree  UMETA(DisplayName = "NumPadThree"),
	EInputBT_NumPadFour  UMETA(DisplayName = "NumPadFour"),
	EInputBT_NumPadFive  UMETA(DisplayName = "NumPadFive"),
	EInputBT_NumPadSix  UMETA(DisplayName = "NumPadSix"),
	EInputBT_NumPadSeven  UMETA(DisplayName = "NumPadSeven"),
	EInputBT_NumPadEight  UMETA(DisplayName = "NumPadEight"),
	EInputBT_NumPadNine  UMETA(DisplayName = "NumPadNine"),

	EInputBT_Multiply  UMETA(DisplayName = "Multiply"),
	EInputBT_Add  UMETA(DisplayName = "Add"),
	EInputBT_Subtract  UMETA(DisplayName = "Subtract"),
	EInputBT_Decimal  UMETA(DisplayName = "Decimal"),
	EInputBT_Divide  UMETA(DisplayName = "Divide"),

	EInputBT_F1  UMETA(DisplayName = "F1"),
	EInputBT_F2  UMETA(DisplayName = "F2"),
	EInputBT_F3  UMETA(DisplayName = "F3"),
	EInputBT_F4  UMETA(DisplayName = "F4"),
	EInputBT_F5  UMETA(DisplayName = "F5"),
	EInputBT_F6  UMETA(DisplayName = "F6"),
	EInputBT_F7  UMETA(DisplayName = "F7"),
	EInputBT_F8  UMETA(DisplayName = "F8"),
	EInputBT_F9  UMETA(DisplayName = "F9"),
	EInputBT_F10  UMETA(DisplayName = "F10"),
	EInputBT_F11  UMETA(DisplayName = "F11"),
	EInputBT_F12  UMETA(DisplayName = "F12"),

	EInputBT_NumLock  UMETA(DisplayName = "NumLock"),

	EInputBT_ScrollLock  UMETA(DisplayName = "ScrollLock"),

	EInputBT_LeftShift  UMETA(DisplayName = "LeftShift"),
	EInputBT_RightShift  UMETA(DisplayName = "RightShift"),
	EInputBT_LeftControl  UMETA(DisplayName = "LeftControl"),
	EInputBT_RightControl  UMETA(DisplayName = "RightControl"),
	EInputBT_LeftAlt  UMETA(DisplayName = "LeftAlt"),
	EInputBT_RightAlt  UMETA(DisplayName = "RightAlt"),
	EInputBT_LeftCommand  UMETA(DisplayName = "LeftCommand"),
	EInputBT_RightCommand  UMETA(DisplayName = "RightCommand"),

	EInputBT_Semicolon  UMETA(DisplayName = "Semicolon"),
	EInputBT_Equals  UMETA(DisplayName = "Equals"),
	EInputBT_Comma  UMETA(DisplayName = "Comma"),
	EInputBT_Underscore  UMETA(DisplayName = "Underscore"),
	EInputBT_Hyphen  UMETA(DisplayName = "Hyphen"),
	EInputBT_Period  UMETA(DisplayName = "Period"),
	EInputBT_Slash  UMETA(DisplayName = "Slash"),
	EInputBT_Tilde  UMETA(DisplayName = "Tilde"),
	EInputBT_LeftBracket  UMETA(DisplayName = "LeftBracket"),
	EInputBT_Backslash  UMETA(DisplayName = "Backslash"),
	EInputBT_RightBracket  UMETA(DisplayName = "RightBracket"),
	EInputBT_Apostrophe  UMETA(DisplayName = "Apostrophe"),

	EInputBT_LeftMouseButton  UMETA(DisplayName = "LeftMouseButton"),
	EInputBT_RightMouseButton  UMETA(DisplayName = "RightMouseButton"),
	EInputBT_MiddleMouseButton  UMETA(DisplayName = "MiddleMouseButton"),
	EInputBT_ThumbMouseButton  UMETA(DisplayName = "ThumbMouseButton"),
	EInputBT_ThumbMouseButton2  UMETA(DisplayName = "ThumbMouseButton2"),

	EInputBT_Gamepad_FaceButton_Bottom  UMETA(DisplayName = "Gamepad_FaceButton_Bottom"),
	EInputBT_Gamepad_FaceButton_Right  UMETA(DisplayName = "Gamepad_FaceButton_Right"),
	EInputBT_Gamepad_FaceButton_Left  UMETA(DisplayName = "Gamepad_FaceButton_Left"),
	EInputBT_Gamepad_FaceButton_Top  UMETA(DisplayName = "Gamepad_FaceButton_Top"),
	EInputBT_Gamepad_Special_Left UMETA(DisplayName = "Gamepad_Special_Left"),
	EInputBT_Gamepad_Special_Right UMETA(DisplayName = "Gamepad_Special_Right"),

	EInputBT_Gamepad_LeftShoulder UMETA(DisplayName = "Gamepad_LeftShoulder"),
	EInputBT_Gamepad_RightShoulder UMETA(DisplayName = "Gamepad_RightShoulder"),
	EInputBT_Gamepad_LeftTrigger UMETA(DisplayName = "Gamepad_LeftTrigger"),
	EInputBT_Gamepad_RightTrigger UMETA(DisplayName = "Gamepad_RightTrigger"),
	EInputBT_Gamepad_LeftThumbstick UMETA(DisplayName = "Gamepad_LeftThumbstick"),
	EInputBT_Gamepad_RightThumbstick UMETA(DisplayName = "Gamepad_RightThumbstick"),
	EInputBT_Gamepad_DPad_Up UMETA(DisplayName = "Gamepad_DPad_Up"),
	EInputBT_Gamepad_DPad_Down UMETA(DisplayName = "Gamepad_DPad_Down"),
	EInputBT_Gamepad_DPad_Left UMETA(DisplayName = "Gamepad_DPad_Left"),
	EInputBT_Gamepad_DPad_Right UMETA(DisplayName = "Gamepad_DPad_Right"),
	EInputBT_Gamepad_LeftStick_Up UMETA(DisplayName = "Gamepad_LeftStick_Up"),
	EInputBT_Gamepad_LeftStick_Down UMETA(DisplayName = "Gamepad_LeftStick_Down"),
	EInputBT_Gamepad_LeftStick_Left UMETA(DisplayName = "Gamepad_LeftStick_Left"),
	EInputBT_Gamepad_LeftStick_Right UMETA(DisplayName = "Gamepad_LeftStick_Right"),
	EInputBT_Gamepad_RightStick_Up UMETA(DisplayName = "Gamepad_RightStick_Up"),
	EInputBT_Gamepad_RightStick_Down UMETA(DisplayName = "Gamepad_RightStick_Down"),
	EInputBT_Gamepad_RightStick_Left UMETA(DisplayName = "Gamepad_RightStick_Left"),
	EInputBT_Gamepad_RightStick_Right UMETA(DisplayName = "Gamepad_RightStick_Right"),
	EInputBT_MAX UMETA(DisplayName = "MAX"),
};